version: '2'
services:
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_VHOST: moltres
    ports:
      - "15672:15672"
      - "5672:5672"

  worker:
    build:
      dockerfile: ./docker/dev/Dockerfile
      context: .
    command: "yarn dev"
    depends_on:
     - rabbitmq
    ports:
      - "3000:3000"
    links:
      - rabbitmq
    volumes:
      - ./:/src